# Generated by Django 2.1.1 on 2018-09-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=100)),
                ('jurisdiction', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.DateTimeField(auto_created=True)),
                ('recordInfo', models.TextField(default='')),
                ('isDelete', models.BooleanField(default=False)),
                ('recordLevel', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.UserInfo')),
            ],
        ),
    ]
