# Generated by Django 2.1.1 on 2018-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verificationCode',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
