# Generated by Django 2.1.1 on 2018-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_userinfo_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
