# Generated by Django 2.1.1 on 2018-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_userinfo_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='recordCondition',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
