# Generated by Django 2.1.1 on 2018-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_userinfo_recordcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='faceLabel',
            field=models.TextField(default=''),
        ),
    ]
