# Generated by Django 2.1.1 on 2018-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_userinfo_facelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningrecord',
            name='recordText',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='faceLabel',
            field=models.TextField(default='[]'),
        ),
    ]
